issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable-all: true
  enable:
    - errorlint
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
output:
  sort-results: true
run:
  timeout: 5m
