issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
        disabled: true
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: context-keys-type
      - name: dot-imports
      - name: early-return
        disabled: true
        arguments:
          - "preserveScope"
      - name: empty-block
        disabled: true
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: increment-decrement
      - name: indent-error-flow
        arguments:
          - "preserveScope"
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
        disabled: true
      - name: superfluous-else
        disabled: true
        arguments:
          - "preserveScope"
      - name: time-naming
        disabled: true
      - name: unexported-return
        disabled: true
      - name: unnecessary-stmt
        disabled: true
      - name: unreachable-code
      - name: unused-parameter
        arguments:
          - allowRegex: "^_"
      - name: use-any
        disabled: true
      - name: var-declaration
      - name: var-naming
        disabled: true
        arguments:
          - ["ID"]
          - ["VM"]
          - - upperCaseConst: true
output:
  sort-results: true
run:
  timeout: 5m
