//go:build ignore

package main

import (
	"bufio"
	"go/format"
	"log"
	"os"
	"strings"
)

func main() {
	mi := make(map[string]string, 0)
	md := []string{}

	parsePlugin := func(element string) {
		items := strings.Split(element, ":")
		if len(items) != 2 {
			// ignore empty lines
			return
		}
		name, repo := items[0], items[1]

		if _, ok := mi[name]; ok {
			log.Fatalf("Duplicate entry %q", name)
		}

		md = append(md, name)
		mi[name] = pluginPath + repo // Default, unless overridden by 3rd arg

		if _, err := os.Stat(pluginFSPath + repo); err != nil { // External package has been given
			mi[name] = repo
		}
	}

	file, err := os.Open(pluginFile)
	if err != nil {
		log.Fatalf("Failed to open %s: %q", pluginFile, err)
	}

	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") {
			continue
		}

		parsePlugin(line)
	}

	for element := range strings.SplitSeq(os.Getenv("COREDNS_PLUGINS"), ",") {
		parsePlugin(element)
	}

	// Separate internal (in-tree) from external (third-party) plugins.
	internalMI := make(map[string]string)
	externalMI := make(map[string]string)

	for name, path := range mi {
		if strings.HasPrefix(path, pluginPath) {
			internalMI[name] = path
		} else {
			externalMI[name] = path
		}
	}

	cleanExternalPluginFiles("core/plugin/")
	genImports("core/plugin/zplugin.go", "plugin", internalMI)

	for name, path := range externalMI {
		genExternalImport("core/plugin/", "plugin", name, path)
	}

	genDirectives("core/dnsserver/zdirectives.go", "dnsserver", md)
}

func genImports(file, pack string, mi map[string]string) {
	outs := header + "package " + pack + "\n\n" + "import ("

	if len(mi) > 0 {
		outs += "\n"
	}

	coreDnsImports := strings.Builder{}
	thirdPartyImports := ""

	outs += "// Include all plugins.\n"

	for _, v := range mi {
		if strings.HasPrefix(v, githubOrg) {
			coreDnsImports.WriteString(`_ "` + v + `"` + "\n")
		} else {
			thirdPartyImports += `_ "` + v + `"` + "\n"
		}
	}

	outs += coreDnsImports.String()

	if thirdPartyImports != "" {
		outs += "\n" + thirdPartyImports
	}

	outs += ")\n"

	if err := formatAndWrite(file, outs); err != nil {
		log.Fatalf("Failed to format and write: %q", err)
	}
}

// cleanExternalPluginFiles removes all previously generated zplugin_ext_*.go files.
func cleanExternalPluginFiles(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("Failed to read dir %s: %v", dir, err)
	}

	for _, e := range entries {
		if strings.HasPrefix(e.Name(), "zplugin_ext_") && strings.HasSuffix(e.Name(), ".go") {
			if err := os.Remove(dir + e.Name()); err != nil {
				log.Fatalf("Failed to remove %s: %v", e.Name(), err)
			}
		}
	}
}

// genExternalImport generates a single-plugin file with a build tag so the
// external import is opt-in via -tags coredns_all or -tags coredns_<name>.
func genExternalImport(dir, pack, name, importPath string) {
	filename := dir + "zplugin_ext_" + name + ".go"
	outs := header +
		"//go:build coredns_all || coredns_" + name + "\n\n" +
		"package " + pack + "\n\n" +
		"import (\n" +
		`_ "` + importPath + `"` + "\n" +
		")\n"

	if err := formatAndWrite(filename, outs); err != nil {
		log.Fatalf("Failed to format and write %s: %q", filename, err)
	}
}

func genDirectives(file, pack string, md []string) {

	outs := strings.Builder{}

	outs.WriteString(header + "package " + pack + "\n\n")
	outs.WriteString(`
// Directives are registered in the order they should be
// executed.
//
// Ordering is VERY important. Every plugin will
// feel the effects of all other plugin below
// (after) them during a request, but they must not
// care what plugin above them are doing.
var Directives = []string{
`)

	for i := range md {
		outs.WriteString(`"` + md[i] + `",` + "\n")
	}

	outs.WriteString("}\n")

	if err := formatAndWrite(file, outs.String()); err != nil {
		log.Fatalf("Failed to format and write: %q", err)
	}
}

func formatAndWrite(file string, data string) error {
	res, err := format.Source([]byte(data))
	if err != nil {
		return err
	}

	if err = os.WriteFile(file, res, 0644); err != nil {
		return err
	}
	return nil
}

const (
	githubOrg    = "github.com/coredns"
	pluginPath   = githubOrg + "/coredns/plugin/"
	pluginFile   = "plugin.cfg"
	pluginFSPath = "plugin/" // Where the plugins are located on the file system
	header       = "// generated by directives_generate.go; DO NOT EDIT\n\n"
)
