ignored = [
    "github.com/mholt/caddy",
    "github.com/mholt/caddy/caddyfile",
    "github.com/mholt/caddy/startupshutdown",
    "github.com/miekg/dns",
    "golang.org/x/net/context",
]
        

[[constraint]]
    name = "github.com/openzipkin/zipkin-go-opentracing"
    version = "v0.2.3"
