// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DnsRR is the predicate function for dnsrr builders.
type DnsRR func(*sql.Selector)

// DnsZone is the predicate function for dnszone builders.
type DnsZone func(*sql.Selector)
