// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coredns/coredns/plugin/sql/ent/dnsrr"
	"github.com/coredns/coredns/plugin/sql/ent/dnszone"
	"github.com/coredns/coredns/plugin/sql/ent/predicate"
	"github.com/rs/xid"
)

// DnsZoneQuery is the builder for querying DnsZone entities.
type DnsZoneQuery struct {
	config
	ctx         *QueryContext
	order       []dnszone.OrderOption
	inters      []Interceptor
	predicates  []predicate.DnsZone
	withRecords *DnsRRQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DnsZoneQuery builder.
func (dzq *DnsZoneQuery) Where(ps ...predicate.DnsZone) *DnsZoneQuery {
	dzq.predicates = append(dzq.predicates, ps...)
	return dzq
}

// Limit the number of records to be returned by this query.
func (dzq *DnsZoneQuery) Limit(limit int) *DnsZoneQuery {
	dzq.ctx.Limit = &limit
	return dzq
}

// Offset to start from.
func (dzq *DnsZoneQuery) Offset(offset int) *DnsZoneQuery {
	dzq.ctx.Offset = &offset
	return dzq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dzq *DnsZoneQuery) Unique(unique bool) *DnsZoneQuery {
	dzq.ctx.Unique = &unique
	return dzq
}

// Order specifies how the records should be ordered.
func (dzq *DnsZoneQuery) Order(o ...dnszone.OrderOption) *DnsZoneQuery {
	dzq.order = append(dzq.order, o...)
	return dzq
}

// QueryRecords chains the current query on the "records" edge.
func (dzq *DnsZoneQuery) QueryRecords() *DnsRRQuery {
	query := (&DnsRRClient{config: dzq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dzq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dzq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dnszone.Table, dnszone.FieldID, selector),
			sqlgraph.To(dnsrr.Table, dnsrr.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dnszone.RecordsTable, dnszone.RecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(dzq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DnsZone entity from the query.
// Returns a *NotFoundError when no DnsZone was found.
func (dzq *DnsZoneQuery) First(ctx context.Context) (*DnsZone, error) {
	nodes, err := dzq.Limit(1).All(setContextOp(ctx, dzq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dnszone.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dzq *DnsZoneQuery) FirstX(ctx context.Context) *DnsZone {
	node, err := dzq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DnsZone ID from the query.
// Returns a *NotFoundError when no DnsZone ID was found.
func (dzq *DnsZoneQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = dzq.Limit(1).IDs(setContextOp(ctx, dzq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dnszone.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dzq *DnsZoneQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := dzq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DnsZone entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DnsZone entity is found.
// Returns a *NotFoundError when no DnsZone entities are found.
func (dzq *DnsZoneQuery) Only(ctx context.Context) (*DnsZone, error) {
	nodes, err := dzq.Limit(2).All(setContextOp(ctx, dzq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dnszone.Label}
	default:
		return nil, &NotSingularError{dnszone.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dzq *DnsZoneQuery) OnlyX(ctx context.Context) *DnsZone {
	node, err := dzq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DnsZone ID in the query.
// Returns a *NotSingularError when more than one DnsZone ID is found.
// Returns a *NotFoundError when no entities are found.
func (dzq *DnsZoneQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = dzq.Limit(2).IDs(setContextOp(ctx, dzq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dnszone.Label}
	default:
		err = &NotSingularError{dnszone.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dzq *DnsZoneQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := dzq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DnsZones.
func (dzq *DnsZoneQuery) All(ctx context.Context) ([]*DnsZone, error) {
	ctx = setContextOp(ctx, dzq.ctx, "All")
	if err := dzq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DnsZone, *DnsZoneQuery]()
	return withInterceptors[[]*DnsZone](ctx, dzq, qr, dzq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dzq *DnsZoneQuery) AllX(ctx context.Context) []*DnsZone {
	nodes, err := dzq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DnsZone IDs.
func (dzq *DnsZoneQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if dzq.ctx.Unique == nil && dzq.path != nil {
		dzq.Unique(true)
	}
	ctx = setContextOp(ctx, dzq.ctx, "IDs")
	if err = dzq.Select(dnszone.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dzq *DnsZoneQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := dzq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dzq *DnsZoneQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dzq.ctx, "Count")
	if err := dzq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dzq, querierCount[*DnsZoneQuery](), dzq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dzq *DnsZoneQuery) CountX(ctx context.Context) int {
	count, err := dzq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dzq *DnsZoneQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dzq.ctx, "Exist")
	switch _, err := dzq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dzq *DnsZoneQuery) ExistX(ctx context.Context) bool {
	exist, err := dzq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DnsZoneQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dzq *DnsZoneQuery) Clone() *DnsZoneQuery {
	if dzq == nil {
		return nil
	}
	return &DnsZoneQuery{
		config:      dzq.config,
		ctx:         dzq.ctx.Clone(),
		order:       append([]dnszone.OrderOption{}, dzq.order...),
		inters:      append([]Interceptor{}, dzq.inters...),
		predicates:  append([]predicate.DnsZone{}, dzq.predicates...),
		withRecords: dzq.withRecords.Clone(),
		// clone intermediate query.
		sql:  dzq.sql.Clone(),
		path: dzq.path,
	}
}

// WithRecords tells the query-builder to eager-load the nodes that are connected to
// the "records" edge. The optional arguments are used to configure the query builder of the edge.
func (dzq *DnsZoneQuery) WithRecords(opts ...func(*DnsRRQuery)) *DnsZoneQuery {
	query := (&DnsRRClient{config: dzq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dzq.withRecords = query
	return dzq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DnsZone.Query().
//		GroupBy(dnszone.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dzq *DnsZoneQuery) GroupBy(field string, fields ...string) *DnsZoneGroupBy {
	dzq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DnsZoneGroupBy{build: dzq}
	grbuild.flds = &dzq.ctx.Fields
	grbuild.label = dnszone.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DnsZone.Query().
//		Select(dnszone.FieldCreatedAt).
//		Scan(ctx, &v)
func (dzq *DnsZoneQuery) Select(fields ...string) *DnsZoneSelect {
	dzq.ctx.Fields = append(dzq.ctx.Fields, fields...)
	sbuild := &DnsZoneSelect{DnsZoneQuery: dzq}
	sbuild.label = dnszone.Label
	sbuild.flds, sbuild.scan = &dzq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DnsZoneSelect configured with the given aggregations.
func (dzq *DnsZoneQuery) Aggregate(fns ...AggregateFunc) *DnsZoneSelect {
	return dzq.Select().Aggregate(fns...)
}

func (dzq *DnsZoneQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dzq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dzq); err != nil {
				return err
			}
		}
	}
	for _, f := range dzq.ctx.Fields {
		if !dnszone.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dzq.path != nil {
		prev, err := dzq.path(ctx)
		if err != nil {
			return err
		}
		dzq.sql = prev
	}
	return nil
}

func (dzq *DnsZoneQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DnsZone, error) {
	var (
		nodes       = []*DnsZone{}
		_spec       = dzq.querySpec()
		loadedTypes = [1]bool{
			dzq.withRecords != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DnsZone).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DnsZone{config: dzq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dzq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dzq.withRecords; query != nil {
		if err := dzq.loadRecords(ctx, query, nodes,
			func(n *DnsZone) { n.Edges.Records = []*DnsRR{} },
			func(n *DnsZone, e *DnsRR) { n.Edges.Records = append(n.Edges.Records, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dzq *DnsZoneQuery) loadRecords(ctx context.Context, query *DnsRRQuery, nodes []*DnsZone, init func(*DnsZone), assign func(*DnsZone, *DnsRR)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*DnsZone)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DnsRR(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(dnszone.RecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.dns_zone_records
		if fk == nil {
			return fmt.Errorf(`foreign-key "dns_zone_records" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dns_zone_records" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (dzq *DnsZoneQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dzq.querySpec()
	_spec.Node.Columns = dzq.ctx.Fields
	if len(dzq.ctx.Fields) > 0 {
		_spec.Unique = dzq.ctx.Unique != nil && *dzq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dzq.driver, _spec)
}

func (dzq *DnsZoneQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dnszone.Table, dnszone.Columns, sqlgraph.NewFieldSpec(dnszone.FieldID, field.TypeString))
	_spec.From = dzq.sql
	if unique := dzq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dzq.path != nil {
		_spec.Unique = true
	}
	if fields := dzq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnszone.FieldID)
		for i := range fields {
			if fields[i] != dnszone.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dzq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dzq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dzq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dzq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dzq *DnsZoneQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dzq.driver.Dialect())
	t1 := builder.Table(dnszone.Table)
	columns := dzq.ctx.Fields
	if len(columns) == 0 {
		columns = dnszone.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dzq.sql != nil {
		selector = dzq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dzq.ctx.Unique != nil && *dzq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dzq.predicates {
		p(selector)
	}
	for _, p := range dzq.order {
		p(selector)
	}
	if offset := dzq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dzq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DnsZoneGroupBy is the group-by builder for DnsZone entities.
type DnsZoneGroupBy struct {
	selector
	build *DnsZoneQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dzgb *DnsZoneGroupBy) Aggregate(fns ...AggregateFunc) *DnsZoneGroupBy {
	dzgb.fns = append(dzgb.fns, fns...)
	return dzgb
}

// Scan applies the selector query and scans the result into the given value.
func (dzgb *DnsZoneGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dzgb.build.ctx, "GroupBy")
	if err := dzgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DnsZoneQuery, *DnsZoneGroupBy](ctx, dzgb.build, dzgb, dzgb.build.inters, v)
}

func (dzgb *DnsZoneGroupBy) sqlScan(ctx context.Context, root *DnsZoneQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dzgb.fns))
	for _, fn := range dzgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dzgb.flds)+len(dzgb.fns))
		for _, f := range *dzgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dzgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dzgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DnsZoneSelect is the builder for selecting fields of DnsZone entities.
type DnsZoneSelect struct {
	*DnsZoneQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dzs *DnsZoneSelect) Aggregate(fns ...AggregateFunc) *DnsZoneSelect {
	dzs.fns = append(dzs.fns, fns...)
	return dzs
}

// Scan applies the selector query and scans the result into the given value.
func (dzs *DnsZoneSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dzs.ctx, "Select")
	if err := dzs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DnsZoneQuery, *DnsZoneSelect](ctx, dzs.DnsZoneQuery, dzs, dzs.inters, v)
}

func (dzs *DnsZoneSelect) sqlScan(ctx context.Context, root *DnsZoneQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dzs.fns))
	for _, fn := range dzs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dzs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dzs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
