// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DNSRrsColumns holds the columns for the "dns_rrs" table.
	DNSRrsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// DNSRrsTable holds the schema information for the "dns_rrs" table.
	DNSRrsTable = &schema.Table{
		Name:       "dns_rrs",
		Columns:    DNSRrsColumns,
		PrimaryKey: []*schema.Column{DNSRrsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DNSRrsTable,
	}
)

func init() {
}
