// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coredns/coredns/plugin/atlas/ent/dnsrr"
	"github.com/coredns/coredns/plugin/atlas/ent/predicate"
)

// DnsRRQuery is the builder for querying DnsRR entities.
type DnsRRQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.DnsRR
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DnsRRQuery builder.
func (drq *DnsRRQuery) Where(ps ...predicate.DnsRR) *DnsRRQuery {
	drq.predicates = append(drq.predicates, ps...)
	return drq
}

// Limit the number of records to be returned by this query.
func (drq *DnsRRQuery) Limit(limit int) *DnsRRQuery {
	drq.ctx.Limit = &limit
	return drq
}

// Offset to start from.
func (drq *DnsRRQuery) Offset(offset int) *DnsRRQuery {
	drq.ctx.Offset = &offset
	return drq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (drq *DnsRRQuery) Unique(unique bool) *DnsRRQuery {
	drq.ctx.Unique = &unique
	return drq
}

// Order specifies how the records should be ordered.
func (drq *DnsRRQuery) Order(o ...OrderFunc) *DnsRRQuery {
	drq.order = append(drq.order, o...)
	return drq
}

// First returns the first DnsRR entity from the query.
// Returns a *NotFoundError when no DnsRR was found.
func (drq *DnsRRQuery) First(ctx context.Context) (*DnsRR, error) {
	nodes, err := drq.Limit(1).All(setContextOp(ctx, drq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dnsrr.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (drq *DnsRRQuery) FirstX(ctx context.Context) *DnsRR {
	node, err := drq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DnsRR ID from the query.
// Returns a *NotFoundError when no DnsRR ID was found.
func (drq *DnsRRQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = drq.Limit(1).IDs(setContextOp(ctx, drq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dnsrr.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (drq *DnsRRQuery) FirstIDX(ctx context.Context) int {
	id, err := drq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DnsRR entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DnsRR entity is found.
// Returns a *NotFoundError when no DnsRR entities are found.
func (drq *DnsRRQuery) Only(ctx context.Context) (*DnsRR, error) {
	nodes, err := drq.Limit(2).All(setContextOp(ctx, drq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dnsrr.Label}
	default:
		return nil, &NotSingularError{dnsrr.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (drq *DnsRRQuery) OnlyX(ctx context.Context) *DnsRR {
	node, err := drq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DnsRR ID in the query.
// Returns a *NotSingularError when more than one DnsRR ID is found.
// Returns a *NotFoundError when no entities are found.
func (drq *DnsRRQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = drq.Limit(2).IDs(setContextOp(ctx, drq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dnsrr.Label}
	default:
		err = &NotSingularError{dnsrr.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (drq *DnsRRQuery) OnlyIDX(ctx context.Context) int {
	id, err := drq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DnsRRs.
func (drq *DnsRRQuery) All(ctx context.Context) ([]*DnsRR, error) {
	ctx = setContextOp(ctx, drq.ctx, "All")
	if err := drq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DnsRR, *DnsRRQuery]()
	return withInterceptors[[]*DnsRR](ctx, drq, qr, drq.inters)
}

// AllX is like All, but panics if an error occurs.
func (drq *DnsRRQuery) AllX(ctx context.Context) []*DnsRR {
	nodes, err := drq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DnsRR IDs.
func (drq *DnsRRQuery) IDs(ctx context.Context) (ids []int, err error) {
	if drq.ctx.Unique == nil && drq.path != nil {
		drq.Unique(true)
	}
	ctx = setContextOp(ctx, drq.ctx, "IDs")
	if err = drq.Select(dnsrr.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (drq *DnsRRQuery) IDsX(ctx context.Context) []int {
	ids, err := drq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (drq *DnsRRQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, drq.ctx, "Count")
	if err := drq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, drq, querierCount[*DnsRRQuery](), drq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (drq *DnsRRQuery) CountX(ctx context.Context) int {
	count, err := drq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (drq *DnsRRQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, drq.ctx, "Exist")
	switch _, err := drq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (drq *DnsRRQuery) ExistX(ctx context.Context) bool {
	exist, err := drq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DnsRRQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (drq *DnsRRQuery) Clone() *DnsRRQuery {
	if drq == nil {
		return nil
	}
	return &DnsRRQuery{
		config:     drq.config,
		ctx:        drq.ctx.Clone(),
		order:      append([]OrderFunc{}, drq.order...),
		inters:     append([]Interceptor{}, drq.inters...),
		predicates: append([]predicate.DnsRR{}, drq.predicates...),
		// clone intermediate query.
		sql:  drq.sql.Clone(),
		path: drq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (drq *DnsRRQuery) GroupBy(field string, fields ...string) *DnsRRGroupBy {
	drq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DnsRRGroupBy{build: drq}
	grbuild.flds = &drq.ctx.Fields
	grbuild.label = dnsrr.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (drq *DnsRRQuery) Select(fields ...string) *DnsRRSelect {
	drq.ctx.Fields = append(drq.ctx.Fields, fields...)
	sbuild := &DnsRRSelect{DnsRRQuery: drq}
	sbuild.label = dnsrr.Label
	sbuild.flds, sbuild.scan = &drq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DnsRRSelect configured with the given aggregations.
func (drq *DnsRRQuery) Aggregate(fns ...AggregateFunc) *DnsRRSelect {
	return drq.Select().Aggregate(fns...)
}

func (drq *DnsRRQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range drq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, drq); err != nil {
				return err
			}
		}
	}
	for _, f := range drq.ctx.Fields {
		if !dnsrr.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if drq.path != nil {
		prev, err := drq.path(ctx)
		if err != nil {
			return err
		}
		drq.sql = prev
	}
	return nil
}

func (drq *DnsRRQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DnsRR, error) {
	var (
		nodes = []*DnsRR{}
		_spec = drq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DnsRR).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DnsRR{config: drq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, drq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (drq *DnsRRQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := drq.querySpec()
	_spec.Node.Columns = drq.ctx.Fields
	if len(drq.ctx.Fields) > 0 {
		_spec.Unique = drq.ctx.Unique != nil && *drq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, drq.driver, _spec)
}

func (drq *DnsRRQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dnsrr.Table, dnsrr.Columns, sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeInt))
	_spec.From = drq.sql
	if unique := drq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if drq.path != nil {
		_spec.Unique = true
	}
	if fields := drq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnsrr.FieldID)
		for i := range fields {
			if fields[i] != dnsrr.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := drq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := drq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := drq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := drq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (drq *DnsRRQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(drq.driver.Dialect())
	t1 := builder.Table(dnsrr.Table)
	columns := drq.ctx.Fields
	if len(columns) == 0 {
		columns = dnsrr.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if drq.sql != nil {
		selector = drq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if drq.ctx.Unique != nil && *drq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range drq.predicates {
		p(selector)
	}
	for _, p := range drq.order {
		p(selector)
	}
	if offset := drq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := drq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DnsRRGroupBy is the group-by builder for DnsRR entities.
type DnsRRGroupBy struct {
	selector
	build *DnsRRQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (drgb *DnsRRGroupBy) Aggregate(fns ...AggregateFunc) *DnsRRGroupBy {
	drgb.fns = append(drgb.fns, fns...)
	return drgb
}

// Scan applies the selector query and scans the result into the given value.
func (drgb *DnsRRGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, drgb.build.ctx, "GroupBy")
	if err := drgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DnsRRQuery, *DnsRRGroupBy](ctx, drgb.build, drgb, drgb.build.inters, v)
}

func (drgb *DnsRRGroupBy) sqlScan(ctx context.Context, root *DnsRRQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(drgb.fns))
	for _, fn := range drgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*drgb.flds)+len(drgb.fns))
		for _, f := range *drgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*drgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := drgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DnsRRSelect is the builder for selecting fields of DnsRR entities.
type DnsRRSelect struct {
	*DnsRRQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (drs *DnsRRSelect) Aggregate(fns ...AggregateFunc) *DnsRRSelect {
	drs.fns = append(drs.fns, fns...)
	return drs
}

// Scan applies the selector query and scans the result into the given value.
func (drs *DnsRRSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, drs.ctx, "Select")
	if err := drs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DnsRRQuery, *DnsRRSelect](ctx, drs.DnsRRQuery, drs, drs.inters, v)
}

func (drs *DnsRRSelect) sqlScan(ctx context.Context, root *DnsRRQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(drs.fns))
	for _, fn := range drs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*drs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := drs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
