// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coredns/coredns/plugin/atlas/ent/dnsrr"
	"github.com/coredns/coredns/plugin/atlas/ent/dnszone"
	"github.com/coredns/coredns/plugin/atlas/ent/predicate"
	"github.com/rs/xid"
)

// DNSZoneUpdate is the builder for updating DNSZone entities.
type DNSZoneUpdate struct {
	config
	hooks    []Hook
	mutation *DNSZoneMutation
}

// Where appends a list predicates to the DNSZoneUpdate builder.
func (dzu *DNSZoneUpdate) Where(ps ...predicate.DNSZone) *DNSZoneUpdate {
	dzu.mutation.Where(ps...)
	return dzu
}

// SetUpdatedAt sets the "updated_at" field.
func (dzu *DNSZoneUpdate) SetUpdatedAt(t time.Time) *DNSZoneUpdate {
	dzu.mutation.SetUpdatedAt(t)
	return dzu
}

// SetRrtype sets the "rrtype" field.
func (dzu *DNSZoneUpdate) SetRrtype(u uint16) *DNSZoneUpdate {
	dzu.mutation.ResetRrtype()
	dzu.mutation.SetRrtype(u)
	return dzu
}

// AddRrtype adds u to the "rrtype" field.
func (dzu *DNSZoneUpdate) AddRrtype(u int16) *DNSZoneUpdate {
	dzu.mutation.AddRrtype(u)
	return dzu
}

// SetClass sets the "class" field.
func (dzu *DNSZoneUpdate) SetClass(u uint16) *DNSZoneUpdate {
	dzu.mutation.ResetClass()
	dzu.mutation.SetClass(u)
	return dzu
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableClass(u *uint16) *DNSZoneUpdate {
	if u != nil {
		dzu.SetClass(*u)
	}
	return dzu
}

// AddClass adds u to the "class" field.
func (dzu *DNSZoneUpdate) AddClass(u int16) *DNSZoneUpdate {
	dzu.mutation.AddClass(u)
	return dzu
}

// SetTTL sets the "ttl" field.
func (dzu *DNSZoneUpdate) SetTTL(u uint32) *DNSZoneUpdate {
	dzu.mutation.ResetTTL()
	dzu.mutation.SetTTL(u)
	return dzu
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableTTL(u *uint32) *DNSZoneUpdate {
	if u != nil {
		dzu.SetTTL(*u)
	}
	return dzu
}

// AddTTL adds u to the "ttl" field.
func (dzu *DNSZoneUpdate) AddTTL(u int32) *DNSZoneUpdate {
	dzu.mutation.AddTTL(u)
	return dzu
}

// SetRdlength sets the "rdlength" field.
func (dzu *DNSZoneUpdate) SetRdlength(u uint16) *DNSZoneUpdate {
	dzu.mutation.ResetRdlength()
	dzu.mutation.SetRdlength(u)
	return dzu
}

// AddRdlength adds u to the "rdlength" field.
func (dzu *DNSZoneUpdate) AddRdlength(u int16) *DNSZoneUpdate {
	dzu.mutation.AddRdlength(u)
	return dzu
}

// SetMbox sets the "mbox" field.
func (dzu *DNSZoneUpdate) SetMbox(s string) *DNSZoneUpdate {
	dzu.mutation.SetMbox(s)
	return dzu
}

// SetSerial sets the "serial" field.
func (dzu *DNSZoneUpdate) SetSerial(u uint32) *DNSZoneUpdate {
	dzu.mutation.ResetSerial()
	dzu.mutation.SetSerial(u)
	return dzu
}

// AddSerial adds u to the "serial" field.
func (dzu *DNSZoneUpdate) AddSerial(u int32) *DNSZoneUpdate {
	dzu.mutation.AddSerial(u)
	return dzu
}

// SetRefresh sets the "refresh" field.
func (dzu *DNSZoneUpdate) SetRefresh(u uint32) *DNSZoneUpdate {
	dzu.mutation.ResetRefresh()
	dzu.mutation.SetRefresh(u)
	return dzu
}

// SetNillableRefresh sets the "refresh" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableRefresh(u *uint32) *DNSZoneUpdate {
	if u != nil {
		dzu.SetRefresh(*u)
	}
	return dzu
}

// AddRefresh adds u to the "refresh" field.
func (dzu *DNSZoneUpdate) AddRefresh(u int32) *DNSZoneUpdate {
	dzu.mutation.AddRefresh(u)
	return dzu
}

// SetRetry sets the "retry" field.
func (dzu *DNSZoneUpdate) SetRetry(u uint32) *DNSZoneUpdate {
	dzu.mutation.ResetRetry()
	dzu.mutation.SetRetry(u)
	return dzu
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableRetry(u *uint32) *DNSZoneUpdate {
	if u != nil {
		dzu.SetRetry(*u)
	}
	return dzu
}

// AddRetry adds u to the "retry" field.
func (dzu *DNSZoneUpdate) AddRetry(u int32) *DNSZoneUpdate {
	dzu.mutation.AddRetry(u)
	return dzu
}

// SetExpire sets the "expire" field.
func (dzu *DNSZoneUpdate) SetExpire(u uint32) *DNSZoneUpdate {
	dzu.mutation.ResetExpire()
	dzu.mutation.SetExpire(u)
	return dzu
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableExpire(u *uint32) *DNSZoneUpdate {
	if u != nil {
		dzu.SetExpire(*u)
	}
	return dzu
}

// AddExpire adds u to the "expire" field.
func (dzu *DNSZoneUpdate) AddExpire(u int32) *DNSZoneUpdate {
	dzu.mutation.AddExpire(u)
	return dzu
}

// SetMinttl sets the "minttl" field.
func (dzu *DNSZoneUpdate) SetMinttl(u uint32) *DNSZoneUpdate {
	dzu.mutation.ResetMinttl()
	dzu.mutation.SetMinttl(u)
	return dzu
}

// SetNillableMinttl sets the "minttl" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableMinttl(u *uint32) *DNSZoneUpdate {
	if u != nil {
		dzu.SetMinttl(*u)
	}
	return dzu
}

// AddMinttl adds u to the "minttl" field.
func (dzu *DNSZoneUpdate) AddMinttl(u int32) *DNSZoneUpdate {
	dzu.mutation.AddMinttl(u)
	return dzu
}

// SetActivated sets the "activated" field.
func (dzu *DNSZoneUpdate) SetActivated(b bool) *DNSZoneUpdate {
	dzu.mutation.SetActivated(b)
	return dzu
}

// SetNillableActivated sets the "activated" field if the given value is not nil.
func (dzu *DNSZoneUpdate) SetNillableActivated(b *bool) *DNSZoneUpdate {
	if b != nil {
		dzu.SetActivated(*b)
	}
	return dzu
}

// AddRecordIDs adds the "records" edge to the DnsRR entity by IDs.
func (dzu *DNSZoneUpdate) AddRecordIDs(ids ...xid.ID) *DNSZoneUpdate {
	dzu.mutation.AddRecordIDs(ids...)
	return dzu
}

// AddRecords adds the "records" edges to the DnsRR entity.
func (dzu *DNSZoneUpdate) AddRecords(d ...*DnsRR) *DNSZoneUpdate {
	ids := make([]xid.ID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dzu.AddRecordIDs(ids...)
}

// Mutation returns the DNSZoneMutation object of the builder.
func (dzu *DNSZoneUpdate) Mutation() *DNSZoneMutation {
	return dzu.mutation
}

// ClearRecords clears all "records" edges to the DnsRR entity.
func (dzu *DNSZoneUpdate) ClearRecords() *DNSZoneUpdate {
	dzu.mutation.ClearRecords()
	return dzu
}

// RemoveRecordIDs removes the "records" edge to DnsRR entities by IDs.
func (dzu *DNSZoneUpdate) RemoveRecordIDs(ids ...xid.ID) *DNSZoneUpdate {
	dzu.mutation.RemoveRecordIDs(ids...)
	return dzu
}

// RemoveRecords removes "records" edges to DnsRR entities.
func (dzu *DNSZoneUpdate) RemoveRecords(d ...*DnsRR) *DNSZoneUpdate {
	ids := make([]xid.ID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dzu.RemoveRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dzu *DNSZoneUpdate) Save(ctx context.Context) (int, error) {
	dzu.defaults()
	return withHooks[int, DNSZoneMutation](ctx, dzu.sqlSave, dzu.mutation, dzu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dzu *DNSZoneUpdate) SaveX(ctx context.Context) int {
	affected, err := dzu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dzu *DNSZoneUpdate) Exec(ctx context.Context) error {
	_, err := dzu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dzu *DNSZoneUpdate) ExecX(ctx context.Context) {
	if err := dzu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dzu *DNSZoneUpdate) defaults() {
	if _, ok := dzu.mutation.UpdatedAt(); !ok {
		v := dnszone.UpdateDefaultUpdatedAt()
		dzu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dzu *DNSZoneUpdate) check() error {
	if v, ok := dzu.mutation.TTL(); ok {
		if err := dnszone.TTLValidator(v); err != nil {
			return &ValidationError{Name: "ttl", err: fmt.Errorf(`ent: validator failed for field "DNSZone.ttl": %w`, err)}
		}
	}
	if v, ok := dzu.mutation.Mbox(); ok {
		if err := dnszone.MboxValidator(v); err != nil {
			return &ValidationError{Name: "mbox", err: fmt.Errorf(`ent: validator failed for field "DNSZone.mbox": %w`, err)}
		}
	}
	if v, ok := dzu.mutation.Refresh(); ok {
		if err := dnszone.RefreshValidator(v); err != nil {
			return &ValidationError{Name: "refresh", err: fmt.Errorf(`ent: validator failed for field "DNSZone.refresh": %w`, err)}
		}
	}
	if v, ok := dzu.mutation.Retry(); ok {
		if err := dnszone.RetryValidator(v); err != nil {
			return &ValidationError{Name: "retry", err: fmt.Errorf(`ent: validator failed for field "DNSZone.retry": %w`, err)}
		}
	}
	if v, ok := dzu.mutation.Expire(); ok {
		if err := dnszone.ExpireValidator(v); err != nil {
			return &ValidationError{Name: "expire", err: fmt.Errorf(`ent: validator failed for field "DNSZone.expire": %w`, err)}
		}
	}
	if v, ok := dzu.mutation.Minttl(); ok {
		if err := dnszone.MinttlValidator(v); err != nil {
			return &ValidationError{Name: "minttl", err: fmt.Errorf(`ent: validator failed for field "DNSZone.minttl": %w`, err)}
		}
	}
	return nil
}

func (dzu *DNSZoneUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dzu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnszone.Table, dnszone.Columns, sqlgraph.NewFieldSpec(dnszone.FieldID, field.TypeString))
	if ps := dzu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dzu.mutation.UpdatedAt(); ok {
		_spec.SetField(dnszone.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := dzu.mutation.Rrtype(); ok {
		_spec.SetField(dnszone.FieldRrtype, field.TypeUint16, value)
	}
	if value, ok := dzu.mutation.AddedRrtype(); ok {
		_spec.AddField(dnszone.FieldRrtype, field.TypeUint16, value)
	}
	if value, ok := dzu.mutation.Class(); ok {
		_spec.SetField(dnszone.FieldClass, field.TypeUint16, value)
	}
	if value, ok := dzu.mutation.AddedClass(); ok {
		_spec.AddField(dnszone.FieldClass, field.TypeUint16, value)
	}
	if value, ok := dzu.mutation.TTL(); ok {
		_spec.SetField(dnszone.FieldTTL, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.AddedTTL(); ok {
		_spec.AddField(dnszone.FieldTTL, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.Rdlength(); ok {
		_spec.SetField(dnszone.FieldRdlength, field.TypeUint16, value)
	}
	if value, ok := dzu.mutation.AddedRdlength(); ok {
		_spec.AddField(dnszone.FieldRdlength, field.TypeUint16, value)
	}
	if value, ok := dzu.mutation.Mbox(); ok {
		_spec.SetField(dnszone.FieldMbox, field.TypeString, value)
	}
	if value, ok := dzu.mutation.Serial(); ok {
		_spec.SetField(dnszone.FieldSerial, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.AddedSerial(); ok {
		_spec.AddField(dnszone.FieldSerial, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.Refresh(); ok {
		_spec.SetField(dnszone.FieldRefresh, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.AddedRefresh(); ok {
		_spec.AddField(dnszone.FieldRefresh, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.Retry(); ok {
		_spec.SetField(dnszone.FieldRetry, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.AddedRetry(); ok {
		_spec.AddField(dnszone.FieldRetry, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.Expire(); ok {
		_spec.SetField(dnszone.FieldExpire, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.AddedExpire(); ok {
		_spec.AddField(dnszone.FieldExpire, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.Minttl(); ok {
		_spec.SetField(dnszone.FieldMinttl, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.AddedMinttl(); ok {
		_spec.AddField(dnszone.FieldMinttl, field.TypeUint32, value)
	}
	if value, ok := dzu.mutation.Activated(); ok {
		_spec.SetField(dnszone.FieldActivated, field.TypeBool, value)
	}
	if dzu.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dzu.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !dzu.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dzu.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dzu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnszone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dzu.mutation.done = true
	return n, nil
}

// DNSZoneUpdateOne is the builder for updating a single DNSZone entity.
type DNSZoneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DNSZoneMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (dzuo *DNSZoneUpdateOne) SetUpdatedAt(t time.Time) *DNSZoneUpdateOne {
	dzuo.mutation.SetUpdatedAt(t)
	return dzuo
}

// SetRrtype sets the "rrtype" field.
func (dzuo *DNSZoneUpdateOne) SetRrtype(u uint16) *DNSZoneUpdateOne {
	dzuo.mutation.ResetRrtype()
	dzuo.mutation.SetRrtype(u)
	return dzuo
}

// AddRrtype adds u to the "rrtype" field.
func (dzuo *DNSZoneUpdateOne) AddRrtype(u int16) *DNSZoneUpdateOne {
	dzuo.mutation.AddRrtype(u)
	return dzuo
}

// SetClass sets the "class" field.
func (dzuo *DNSZoneUpdateOne) SetClass(u uint16) *DNSZoneUpdateOne {
	dzuo.mutation.ResetClass()
	dzuo.mutation.SetClass(u)
	return dzuo
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableClass(u *uint16) *DNSZoneUpdateOne {
	if u != nil {
		dzuo.SetClass(*u)
	}
	return dzuo
}

// AddClass adds u to the "class" field.
func (dzuo *DNSZoneUpdateOne) AddClass(u int16) *DNSZoneUpdateOne {
	dzuo.mutation.AddClass(u)
	return dzuo
}

// SetTTL sets the "ttl" field.
func (dzuo *DNSZoneUpdateOne) SetTTL(u uint32) *DNSZoneUpdateOne {
	dzuo.mutation.ResetTTL()
	dzuo.mutation.SetTTL(u)
	return dzuo
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableTTL(u *uint32) *DNSZoneUpdateOne {
	if u != nil {
		dzuo.SetTTL(*u)
	}
	return dzuo
}

// AddTTL adds u to the "ttl" field.
func (dzuo *DNSZoneUpdateOne) AddTTL(u int32) *DNSZoneUpdateOne {
	dzuo.mutation.AddTTL(u)
	return dzuo
}

// SetRdlength sets the "rdlength" field.
func (dzuo *DNSZoneUpdateOne) SetRdlength(u uint16) *DNSZoneUpdateOne {
	dzuo.mutation.ResetRdlength()
	dzuo.mutation.SetRdlength(u)
	return dzuo
}

// AddRdlength adds u to the "rdlength" field.
func (dzuo *DNSZoneUpdateOne) AddRdlength(u int16) *DNSZoneUpdateOne {
	dzuo.mutation.AddRdlength(u)
	return dzuo
}

// SetMbox sets the "mbox" field.
func (dzuo *DNSZoneUpdateOne) SetMbox(s string) *DNSZoneUpdateOne {
	dzuo.mutation.SetMbox(s)
	return dzuo
}

// SetSerial sets the "serial" field.
func (dzuo *DNSZoneUpdateOne) SetSerial(u uint32) *DNSZoneUpdateOne {
	dzuo.mutation.ResetSerial()
	dzuo.mutation.SetSerial(u)
	return dzuo
}

// AddSerial adds u to the "serial" field.
func (dzuo *DNSZoneUpdateOne) AddSerial(u int32) *DNSZoneUpdateOne {
	dzuo.mutation.AddSerial(u)
	return dzuo
}

// SetRefresh sets the "refresh" field.
func (dzuo *DNSZoneUpdateOne) SetRefresh(u uint32) *DNSZoneUpdateOne {
	dzuo.mutation.ResetRefresh()
	dzuo.mutation.SetRefresh(u)
	return dzuo
}

// SetNillableRefresh sets the "refresh" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableRefresh(u *uint32) *DNSZoneUpdateOne {
	if u != nil {
		dzuo.SetRefresh(*u)
	}
	return dzuo
}

// AddRefresh adds u to the "refresh" field.
func (dzuo *DNSZoneUpdateOne) AddRefresh(u int32) *DNSZoneUpdateOne {
	dzuo.mutation.AddRefresh(u)
	return dzuo
}

// SetRetry sets the "retry" field.
func (dzuo *DNSZoneUpdateOne) SetRetry(u uint32) *DNSZoneUpdateOne {
	dzuo.mutation.ResetRetry()
	dzuo.mutation.SetRetry(u)
	return dzuo
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableRetry(u *uint32) *DNSZoneUpdateOne {
	if u != nil {
		dzuo.SetRetry(*u)
	}
	return dzuo
}

// AddRetry adds u to the "retry" field.
func (dzuo *DNSZoneUpdateOne) AddRetry(u int32) *DNSZoneUpdateOne {
	dzuo.mutation.AddRetry(u)
	return dzuo
}

// SetExpire sets the "expire" field.
func (dzuo *DNSZoneUpdateOne) SetExpire(u uint32) *DNSZoneUpdateOne {
	dzuo.mutation.ResetExpire()
	dzuo.mutation.SetExpire(u)
	return dzuo
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableExpire(u *uint32) *DNSZoneUpdateOne {
	if u != nil {
		dzuo.SetExpire(*u)
	}
	return dzuo
}

// AddExpire adds u to the "expire" field.
func (dzuo *DNSZoneUpdateOne) AddExpire(u int32) *DNSZoneUpdateOne {
	dzuo.mutation.AddExpire(u)
	return dzuo
}

// SetMinttl sets the "minttl" field.
func (dzuo *DNSZoneUpdateOne) SetMinttl(u uint32) *DNSZoneUpdateOne {
	dzuo.mutation.ResetMinttl()
	dzuo.mutation.SetMinttl(u)
	return dzuo
}

// SetNillableMinttl sets the "minttl" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableMinttl(u *uint32) *DNSZoneUpdateOne {
	if u != nil {
		dzuo.SetMinttl(*u)
	}
	return dzuo
}

// AddMinttl adds u to the "minttl" field.
func (dzuo *DNSZoneUpdateOne) AddMinttl(u int32) *DNSZoneUpdateOne {
	dzuo.mutation.AddMinttl(u)
	return dzuo
}

// SetActivated sets the "activated" field.
func (dzuo *DNSZoneUpdateOne) SetActivated(b bool) *DNSZoneUpdateOne {
	dzuo.mutation.SetActivated(b)
	return dzuo
}

// SetNillableActivated sets the "activated" field if the given value is not nil.
func (dzuo *DNSZoneUpdateOne) SetNillableActivated(b *bool) *DNSZoneUpdateOne {
	if b != nil {
		dzuo.SetActivated(*b)
	}
	return dzuo
}

// AddRecordIDs adds the "records" edge to the DnsRR entity by IDs.
func (dzuo *DNSZoneUpdateOne) AddRecordIDs(ids ...xid.ID) *DNSZoneUpdateOne {
	dzuo.mutation.AddRecordIDs(ids...)
	return dzuo
}

// AddRecords adds the "records" edges to the DnsRR entity.
func (dzuo *DNSZoneUpdateOne) AddRecords(d ...*DnsRR) *DNSZoneUpdateOne {
	ids := make([]xid.ID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dzuo.AddRecordIDs(ids...)
}

// Mutation returns the DNSZoneMutation object of the builder.
func (dzuo *DNSZoneUpdateOne) Mutation() *DNSZoneMutation {
	return dzuo.mutation
}

// ClearRecords clears all "records" edges to the DnsRR entity.
func (dzuo *DNSZoneUpdateOne) ClearRecords() *DNSZoneUpdateOne {
	dzuo.mutation.ClearRecords()
	return dzuo
}

// RemoveRecordIDs removes the "records" edge to DnsRR entities by IDs.
func (dzuo *DNSZoneUpdateOne) RemoveRecordIDs(ids ...xid.ID) *DNSZoneUpdateOne {
	dzuo.mutation.RemoveRecordIDs(ids...)
	return dzuo
}

// RemoveRecords removes "records" edges to DnsRR entities.
func (dzuo *DNSZoneUpdateOne) RemoveRecords(d ...*DnsRR) *DNSZoneUpdateOne {
	ids := make([]xid.ID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dzuo.RemoveRecordIDs(ids...)
}

// Where appends a list predicates to the DNSZoneUpdate builder.
func (dzuo *DNSZoneUpdateOne) Where(ps ...predicate.DNSZone) *DNSZoneUpdateOne {
	dzuo.mutation.Where(ps...)
	return dzuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dzuo *DNSZoneUpdateOne) Select(field string, fields ...string) *DNSZoneUpdateOne {
	dzuo.fields = append([]string{field}, fields...)
	return dzuo
}

// Save executes the query and returns the updated DNSZone entity.
func (dzuo *DNSZoneUpdateOne) Save(ctx context.Context) (*DNSZone, error) {
	dzuo.defaults()
	return withHooks[*DNSZone, DNSZoneMutation](ctx, dzuo.sqlSave, dzuo.mutation, dzuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dzuo *DNSZoneUpdateOne) SaveX(ctx context.Context) *DNSZone {
	node, err := dzuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dzuo *DNSZoneUpdateOne) Exec(ctx context.Context) error {
	_, err := dzuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dzuo *DNSZoneUpdateOne) ExecX(ctx context.Context) {
	if err := dzuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dzuo *DNSZoneUpdateOne) defaults() {
	if _, ok := dzuo.mutation.UpdatedAt(); !ok {
		v := dnszone.UpdateDefaultUpdatedAt()
		dzuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dzuo *DNSZoneUpdateOne) check() error {
	if v, ok := dzuo.mutation.TTL(); ok {
		if err := dnszone.TTLValidator(v); err != nil {
			return &ValidationError{Name: "ttl", err: fmt.Errorf(`ent: validator failed for field "DNSZone.ttl": %w`, err)}
		}
	}
	if v, ok := dzuo.mutation.Mbox(); ok {
		if err := dnszone.MboxValidator(v); err != nil {
			return &ValidationError{Name: "mbox", err: fmt.Errorf(`ent: validator failed for field "DNSZone.mbox": %w`, err)}
		}
	}
	if v, ok := dzuo.mutation.Refresh(); ok {
		if err := dnszone.RefreshValidator(v); err != nil {
			return &ValidationError{Name: "refresh", err: fmt.Errorf(`ent: validator failed for field "DNSZone.refresh": %w`, err)}
		}
	}
	if v, ok := dzuo.mutation.Retry(); ok {
		if err := dnszone.RetryValidator(v); err != nil {
			return &ValidationError{Name: "retry", err: fmt.Errorf(`ent: validator failed for field "DNSZone.retry": %w`, err)}
		}
	}
	if v, ok := dzuo.mutation.Expire(); ok {
		if err := dnszone.ExpireValidator(v); err != nil {
			return &ValidationError{Name: "expire", err: fmt.Errorf(`ent: validator failed for field "DNSZone.expire": %w`, err)}
		}
	}
	if v, ok := dzuo.mutation.Minttl(); ok {
		if err := dnszone.MinttlValidator(v); err != nil {
			return &ValidationError{Name: "minttl", err: fmt.Errorf(`ent: validator failed for field "DNSZone.minttl": %w`, err)}
		}
	}
	return nil
}

func (dzuo *DNSZoneUpdateOne) sqlSave(ctx context.Context) (_node *DNSZone, err error) {
	if err := dzuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnszone.Table, dnszone.Columns, sqlgraph.NewFieldSpec(dnszone.FieldID, field.TypeString))
	id, ok := dzuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DNSZone.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dzuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnszone.FieldID)
		for _, f := range fields {
			if !dnszone.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dnszone.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dzuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dzuo.mutation.UpdatedAt(); ok {
		_spec.SetField(dnszone.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := dzuo.mutation.Rrtype(); ok {
		_spec.SetField(dnszone.FieldRrtype, field.TypeUint16, value)
	}
	if value, ok := dzuo.mutation.AddedRrtype(); ok {
		_spec.AddField(dnszone.FieldRrtype, field.TypeUint16, value)
	}
	if value, ok := dzuo.mutation.Class(); ok {
		_spec.SetField(dnszone.FieldClass, field.TypeUint16, value)
	}
	if value, ok := dzuo.mutation.AddedClass(); ok {
		_spec.AddField(dnszone.FieldClass, field.TypeUint16, value)
	}
	if value, ok := dzuo.mutation.TTL(); ok {
		_spec.SetField(dnszone.FieldTTL, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.AddedTTL(); ok {
		_spec.AddField(dnszone.FieldTTL, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.Rdlength(); ok {
		_spec.SetField(dnszone.FieldRdlength, field.TypeUint16, value)
	}
	if value, ok := dzuo.mutation.AddedRdlength(); ok {
		_spec.AddField(dnszone.FieldRdlength, field.TypeUint16, value)
	}
	if value, ok := dzuo.mutation.Mbox(); ok {
		_spec.SetField(dnszone.FieldMbox, field.TypeString, value)
	}
	if value, ok := dzuo.mutation.Serial(); ok {
		_spec.SetField(dnszone.FieldSerial, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.AddedSerial(); ok {
		_spec.AddField(dnszone.FieldSerial, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.Refresh(); ok {
		_spec.SetField(dnszone.FieldRefresh, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.AddedRefresh(); ok {
		_spec.AddField(dnszone.FieldRefresh, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.Retry(); ok {
		_spec.SetField(dnszone.FieldRetry, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.AddedRetry(); ok {
		_spec.AddField(dnszone.FieldRetry, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.Expire(); ok {
		_spec.SetField(dnszone.FieldExpire, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.AddedExpire(); ok {
		_spec.AddField(dnszone.FieldExpire, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.Minttl(); ok {
		_spec.SetField(dnszone.FieldMinttl, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.AddedMinttl(); ok {
		_spec.AddField(dnszone.FieldMinttl, field.TypeUint32, value)
	}
	if value, ok := dzuo.mutation.Activated(); ok {
		_spec.SetField(dnszone.FieldActivated, field.TypeBool, value)
	}
	if dzuo.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dzuo.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !dzuo.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dzuo.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DNSZone{config: dzuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dzuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnszone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dzuo.mutation.done = true
	return _node, nil
}
