// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coredns/coredns/plugin/atlas/ent/dnsrr"
	"github.com/coredns/coredns/plugin/atlas/ent/dnszone"
	"github.com/rs/xid"
)

// DnsZoneCreate is the builder for creating a DnsZone entity.
type DnsZoneCreate struct {
	config
	mutation *DnsZoneMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (dzc *DnsZoneCreate) SetCreatedAt(t time.Time) *DnsZoneCreate {
	dzc.mutation.SetCreatedAt(t)
	return dzc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableCreatedAt(t *time.Time) *DnsZoneCreate {
	if t != nil {
		dzc.SetCreatedAt(*t)
	}
	return dzc
}

// SetUpdatedAt sets the "updated_at" field.
func (dzc *DnsZoneCreate) SetUpdatedAt(t time.Time) *DnsZoneCreate {
	dzc.mutation.SetUpdatedAt(t)
	return dzc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableUpdatedAt(t *time.Time) *DnsZoneCreate {
	if t != nil {
		dzc.SetUpdatedAt(*t)
	}
	return dzc
}

// SetName sets the "name" field.
func (dzc *DnsZoneCreate) SetName(s string) *DnsZoneCreate {
	dzc.mutation.SetName(s)
	return dzc
}

// SetRrtype sets the "rrtype" field.
func (dzc *DnsZoneCreate) SetRrtype(u uint16) *DnsZoneCreate {
	dzc.mutation.SetRrtype(u)
	return dzc
}

// SetNillableRrtype sets the "rrtype" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableRrtype(u *uint16) *DnsZoneCreate {
	if u != nil {
		dzc.SetRrtype(*u)
	}
	return dzc
}

// SetClass sets the "class" field.
func (dzc *DnsZoneCreate) SetClass(u uint16) *DnsZoneCreate {
	dzc.mutation.SetClass(u)
	return dzc
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableClass(u *uint16) *DnsZoneCreate {
	if u != nil {
		dzc.SetClass(*u)
	}
	return dzc
}

// SetTTL sets the "ttl" field.
func (dzc *DnsZoneCreate) SetTTL(u uint32) *DnsZoneCreate {
	dzc.mutation.SetTTL(u)
	return dzc
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableTTL(u *uint32) *DnsZoneCreate {
	if u != nil {
		dzc.SetTTL(*u)
	}
	return dzc
}

// SetNs sets the "ns" field.
func (dzc *DnsZoneCreate) SetNs(s string) *DnsZoneCreate {
	dzc.mutation.SetNs(s)
	return dzc
}

// SetMbox sets the "mbox" field.
func (dzc *DnsZoneCreate) SetMbox(s string) *DnsZoneCreate {
	dzc.mutation.SetMbox(s)
	return dzc
}

// SetSerial sets the "serial" field.
func (dzc *DnsZoneCreate) SetSerial(u uint32) *DnsZoneCreate {
	dzc.mutation.SetSerial(u)
	return dzc
}

// SetRefresh sets the "refresh" field.
func (dzc *DnsZoneCreate) SetRefresh(u uint32) *DnsZoneCreate {
	dzc.mutation.SetRefresh(u)
	return dzc
}

// SetNillableRefresh sets the "refresh" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableRefresh(u *uint32) *DnsZoneCreate {
	if u != nil {
		dzc.SetRefresh(*u)
	}
	return dzc
}

// SetRetry sets the "retry" field.
func (dzc *DnsZoneCreate) SetRetry(u uint32) *DnsZoneCreate {
	dzc.mutation.SetRetry(u)
	return dzc
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableRetry(u *uint32) *DnsZoneCreate {
	if u != nil {
		dzc.SetRetry(*u)
	}
	return dzc
}

// SetExpire sets the "expire" field.
func (dzc *DnsZoneCreate) SetExpire(u uint32) *DnsZoneCreate {
	dzc.mutation.SetExpire(u)
	return dzc
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableExpire(u *uint32) *DnsZoneCreate {
	if u != nil {
		dzc.SetExpire(*u)
	}
	return dzc
}

// SetMinttl sets the "minttl" field.
func (dzc *DnsZoneCreate) SetMinttl(u uint32) *DnsZoneCreate {
	dzc.mutation.SetMinttl(u)
	return dzc
}

// SetNillableMinttl sets the "minttl" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableMinttl(u *uint32) *DnsZoneCreate {
	if u != nil {
		dzc.SetMinttl(*u)
	}
	return dzc
}

// SetActivated sets the "activated" field.
func (dzc *DnsZoneCreate) SetActivated(b bool) *DnsZoneCreate {
	dzc.mutation.SetActivated(b)
	return dzc
}

// SetNillableActivated sets the "activated" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableActivated(b *bool) *DnsZoneCreate {
	if b != nil {
		dzc.SetActivated(*b)
	}
	return dzc
}

// SetID sets the "id" field.
func (dzc *DnsZoneCreate) SetID(x xid.ID) *DnsZoneCreate {
	dzc.mutation.SetID(x)
	return dzc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dzc *DnsZoneCreate) SetNillableID(x *xid.ID) *DnsZoneCreate {
	if x != nil {
		dzc.SetID(*x)
	}
	return dzc
}

// AddRecordIDs adds the "records" edge to the DnsRR entity by IDs.
func (dzc *DnsZoneCreate) AddRecordIDs(ids ...xid.ID) *DnsZoneCreate {
	dzc.mutation.AddRecordIDs(ids...)
	return dzc
}

// AddRecords adds the "records" edges to the DnsRR entity.
func (dzc *DnsZoneCreate) AddRecords(d ...*DnsRR) *DnsZoneCreate {
	ids := make([]xid.ID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dzc.AddRecordIDs(ids...)
}

// Mutation returns the DnsZoneMutation object of the builder.
func (dzc *DnsZoneCreate) Mutation() *DnsZoneMutation {
	return dzc.mutation
}

// Save creates the DnsZone in the database.
func (dzc *DnsZoneCreate) Save(ctx context.Context) (*DnsZone, error) {
	dzc.defaults()
	return withHooks[*DnsZone, DnsZoneMutation](ctx, dzc.sqlSave, dzc.mutation, dzc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dzc *DnsZoneCreate) SaveX(ctx context.Context) *DnsZone {
	v, err := dzc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dzc *DnsZoneCreate) Exec(ctx context.Context) error {
	_, err := dzc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dzc *DnsZoneCreate) ExecX(ctx context.Context) {
	if err := dzc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dzc *DnsZoneCreate) defaults() {
	if _, ok := dzc.mutation.CreatedAt(); !ok {
		v := dnszone.DefaultCreatedAt()
		dzc.mutation.SetCreatedAt(v)
	}
	if _, ok := dzc.mutation.UpdatedAt(); !ok {
		v := dnszone.DefaultUpdatedAt()
		dzc.mutation.SetUpdatedAt(v)
	}
	if _, ok := dzc.mutation.Rrtype(); !ok {
		v := dnszone.DefaultRrtype
		dzc.mutation.SetRrtype(v)
	}
	if _, ok := dzc.mutation.Class(); !ok {
		v := dnszone.DefaultClass
		dzc.mutation.SetClass(v)
	}
	if _, ok := dzc.mutation.TTL(); !ok {
		v := dnszone.DefaultTTL
		dzc.mutation.SetTTL(v)
	}
	if _, ok := dzc.mutation.Refresh(); !ok {
		v := dnszone.DefaultRefresh
		dzc.mutation.SetRefresh(v)
	}
	if _, ok := dzc.mutation.Retry(); !ok {
		v := dnszone.DefaultRetry
		dzc.mutation.SetRetry(v)
	}
	if _, ok := dzc.mutation.Expire(); !ok {
		v := dnszone.DefaultExpire
		dzc.mutation.SetExpire(v)
	}
	if _, ok := dzc.mutation.Minttl(); !ok {
		v := dnszone.DefaultMinttl
		dzc.mutation.SetMinttl(v)
	}
	if _, ok := dzc.mutation.Activated(); !ok {
		v := dnszone.DefaultActivated
		dzc.mutation.SetActivated(v)
	}
	if _, ok := dzc.mutation.ID(); !ok {
		v := dnszone.DefaultID()
		dzc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dzc *DnsZoneCreate) check() error {
	if _, ok := dzc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DnsZone.created_at"`)}
	}
	if _, ok := dzc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DnsZone.updated_at"`)}
	}
	if _, ok := dzc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DnsZone.name"`)}
	}
	if v, ok := dzc.mutation.Name(); ok {
		if err := dnszone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DnsZone.name": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Rrtype(); !ok {
		return &ValidationError{Name: "rrtype", err: errors.New(`ent: missing required field "DnsZone.rrtype"`)}
	}
	if _, ok := dzc.mutation.Class(); !ok {
		return &ValidationError{Name: "class", err: errors.New(`ent: missing required field "DnsZone.class"`)}
	}
	if _, ok := dzc.mutation.TTL(); !ok {
		return &ValidationError{Name: "ttl", err: errors.New(`ent: missing required field "DnsZone.ttl"`)}
	}
	if v, ok := dzc.mutation.TTL(); ok {
		if err := dnszone.TTLValidator(v); err != nil {
			return &ValidationError{Name: "ttl", err: fmt.Errorf(`ent: validator failed for field "DnsZone.ttl": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Ns(); !ok {
		return &ValidationError{Name: "ns", err: errors.New(`ent: missing required field "DnsZone.ns"`)}
	}
	if v, ok := dzc.mutation.Ns(); ok {
		if err := dnszone.NsValidator(v); err != nil {
			return &ValidationError{Name: "ns", err: fmt.Errorf(`ent: validator failed for field "DnsZone.ns": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Mbox(); !ok {
		return &ValidationError{Name: "mbox", err: errors.New(`ent: missing required field "DnsZone.mbox"`)}
	}
	if v, ok := dzc.mutation.Mbox(); ok {
		if err := dnszone.MboxValidator(v); err != nil {
			return &ValidationError{Name: "mbox", err: fmt.Errorf(`ent: validator failed for field "DnsZone.mbox": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Serial(); !ok {
		return &ValidationError{Name: "serial", err: errors.New(`ent: missing required field "DnsZone.serial"`)}
	}
	if _, ok := dzc.mutation.Refresh(); !ok {
		return &ValidationError{Name: "refresh", err: errors.New(`ent: missing required field "DnsZone.refresh"`)}
	}
	if v, ok := dzc.mutation.Refresh(); ok {
		if err := dnszone.RefreshValidator(v); err != nil {
			return &ValidationError{Name: "refresh", err: fmt.Errorf(`ent: validator failed for field "DnsZone.refresh": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Retry(); !ok {
		return &ValidationError{Name: "retry", err: errors.New(`ent: missing required field "DnsZone.retry"`)}
	}
	if v, ok := dzc.mutation.Retry(); ok {
		if err := dnszone.RetryValidator(v); err != nil {
			return &ValidationError{Name: "retry", err: fmt.Errorf(`ent: validator failed for field "DnsZone.retry": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Expire(); !ok {
		return &ValidationError{Name: "expire", err: errors.New(`ent: missing required field "DnsZone.expire"`)}
	}
	if v, ok := dzc.mutation.Expire(); ok {
		if err := dnszone.ExpireValidator(v); err != nil {
			return &ValidationError{Name: "expire", err: fmt.Errorf(`ent: validator failed for field "DnsZone.expire": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Minttl(); !ok {
		return &ValidationError{Name: "minttl", err: errors.New(`ent: missing required field "DnsZone.minttl"`)}
	}
	if v, ok := dzc.mutation.Minttl(); ok {
		if err := dnszone.MinttlValidator(v); err != nil {
			return &ValidationError{Name: "minttl", err: fmt.Errorf(`ent: validator failed for field "DnsZone.minttl": %w`, err)}
		}
	}
	if _, ok := dzc.mutation.Activated(); !ok {
		return &ValidationError{Name: "activated", err: errors.New(`ent: missing required field "DnsZone.activated"`)}
	}
	return nil
}

func (dzc *DnsZoneCreate) sqlSave(ctx context.Context) (*DnsZone, error) {
	if err := dzc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dzc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dzc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dzc.mutation.id = &_node.ID
	dzc.mutation.done = true
	return _node, nil
}

func (dzc *DnsZoneCreate) createSpec() (*DnsZone, *sqlgraph.CreateSpec) {
	var (
		_node = &DnsZone{config: dzc.config}
		_spec = sqlgraph.NewCreateSpec(dnszone.Table, sqlgraph.NewFieldSpec(dnszone.FieldID, field.TypeString))
	)
	_spec.OnConflict = dzc.conflict
	if id, ok := dzc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dzc.mutation.CreatedAt(); ok {
		_spec.SetField(dnszone.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dzc.mutation.UpdatedAt(); ok {
		_spec.SetField(dnszone.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := dzc.mutation.Name(); ok {
		_spec.SetField(dnszone.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dzc.mutation.Rrtype(); ok {
		_spec.SetField(dnszone.FieldRrtype, field.TypeUint16, value)
		_node.Rrtype = value
	}
	if value, ok := dzc.mutation.Class(); ok {
		_spec.SetField(dnszone.FieldClass, field.TypeUint16, value)
		_node.Class = value
	}
	if value, ok := dzc.mutation.TTL(); ok {
		_spec.SetField(dnszone.FieldTTL, field.TypeUint32, value)
		_node.TTL = value
	}
	if value, ok := dzc.mutation.Ns(); ok {
		_spec.SetField(dnszone.FieldNs, field.TypeString, value)
		_node.Ns = value
	}
	if value, ok := dzc.mutation.Mbox(); ok {
		_spec.SetField(dnszone.FieldMbox, field.TypeString, value)
		_node.Mbox = value
	}
	if value, ok := dzc.mutation.Serial(); ok {
		_spec.SetField(dnszone.FieldSerial, field.TypeUint32, value)
		_node.Serial = value
	}
	if value, ok := dzc.mutation.Refresh(); ok {
		_spec.SetField(dnszone.FieldRefresh, field.TypeUint32, value)
		_node.Refresh = value
	}
	if value, ok := dzc.mutation.Retry(); ok {
		_spec.SetField(dnszone.FieldRetry, field.TypeUint32, value)
		_node.Retry = value
	}
	if value, ok := dzc.mutation.Expire(); ok {
		_spec.SetField(dnszone.FieldExpire, field.TypeUint32, value)
		_node.Expire = value
	}
	if value, ok := dzc.mutation.Minttl(); ok {
		_spec.SetField(dnszone.FieldMinttl, field.TypeUint32, value)
		_node.Minttl = value
	}
	if value, ok := dzc.mutation.Activated(); ok {
		_spec.SetField(dnszone.FieldActivated, field.TypeBool, value)
		_node.Activated = value
	}
	if nodes := dzc.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnszone.RecordsTable,
			Columns: []string{dnszone.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsrr.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DnsZone.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DnsZoneUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (dzc *DnsZoneCreate) OnConflict(opts ...sql.ConflictOption) *DnsZoneUpsertOne {
	dzc.conflict = opts
	return &DnsZoneUpsertOne{
		create: dzc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DnsZone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dzc *DnsZoneCreate) OnConflictColumns(columns ...string) *DnsZoneUpsertOne {
	dzc.conflict = append(dzc.conflict, sql.ConflictColumns(columns...))
	return &DnsZoneUpsertOne{
		create: dzc,
	}
}

type (
	// DnsZoneUpsertOne is the builder for "upsert"-ing
	//  one DnsZone node.
	DnsZoneUpsertOne struct {
		create *DnsZoneCreate
	}

	// DnsZoneUpsert is the "OnConflict" setter.
	DnsZoneUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DnsZoneUpsert) SetUpdatedAt(v time.Time) *DnsZoneUpsert {
	u.Set(dnszone.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateUpdatedAt() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldUpdatedAt)
	return u
}

// SetRrtype sets the "rrtype" field.
func (u *DnsZoneUpsert) SetRrtype(v uint16) *DnsZoneUpsert {
	u.Set(dnszone.FieldRrtype, v)
	return u
}

// UpdateRrtype sets the "rrtype" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateRrtype() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldRrtype)
	return u
}

// AddRrtype adds v to the "rrtype" field.
func (u *DnsZoneUpsert) AddRrtype(v uint16) *DnsZoneUpsert {
	u.Add(dnszone.FieldRrtype, v)
	return u
}

// SetClass sets the "class" field.
func (u *DnsZoneUpsert) SetClass(v uint16) *DnsZoneUpsert {
	u.Set(dnszone.FieldClass, v)
	return u
}

// UpdateClass sets the "class" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateClass() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldClass)
	return u
}

// AddClass adds v to the "class" field.
func (u *DnsZoneUpsert) AddClass(v uint16) *DnsZoneUpsert {
	u.Add(dnszone.FieldClass, v)
	return u
}

// SetTTL sets the "ttl" field.
func (u *DnsZoneUpsert) SetTTL(v uint32) *DnsZoneUpsert {
	u.Set(dnszone.FieldTTL, v)
	return u
}

// UpdateTTL sets the "ttl" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateTTL() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldTTL)
	return u
}

// AddTTL adds v to the "ttl" field.
func (u *DnsZoneUpsert) AddTTL(v uint32) *DnsZoneUpsert {
	u.Add(dnszone.FieldTTL, v)
	return u
}

// SetNs sets the "ns" field.
func (u *DnsZoneUpsert) SetNs(v string) *DnsZoneUpsert {
	u.Set(dnszone.FieldNs, v)
	return u
}

// UpdateNs sets the "ns" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateNs() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldNs)
	return u
}

// SetMbox sets the "mbox" field.
func (u *DnsZoneUpsert) SetMbox(v string) *DnsZoneUpsert {
	u.Set(dnszone.FieldMbox, v)
	return u
}

// UpdateMbox sets the "mbox" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateMbox() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldMbox)
	return u
}

// SetSerial sets the "serial" field.
func (u *DnsZoneUpsert) SetSerial(v uint32) *DnsZoneUpsert {
	u.Set(dnszone.FieldSerial, v)
	return u
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateSerial() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldSerial)
	return u
}

// AddSerial adds v to the "serial" field.
func (u *DnsZoneUpsert) AddSerial(v uint32) *DnsZoneUpsert {
	u.Add(dnszone.FieldSerial, v)
	return u
}

// SetRefresh sets the "refresh" field.
func (u *DnsZoneUpsert) SetRefresh(v uint32) *DnsZoneUpsert {
	u.Set(dnszone.FieldRefresh, v)
	return u
}

// UpdateRefresh sets the "refresh" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateRefresh() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldRefresh)
	return u
}

// AddRefresh adds v to the "refresh" field.
func (u *DnsZoneUpsert) AddRefresh(v uint32) *DnsZoneUpsert {
	u.Add(dnszone.FieldRefresh, v)
	return u
}

// SetRetry sets the "retry" field.
func (u *DnsZoneUpsert) SetRetry(v uint32) *DnsZoneUpsert {
	u.Set(dnszone.FieldRetry, v)
	return u
}

// UpdateRetry sets the "retry" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateRetry() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldRetry)
	return u
}

// AddRetry adds v to the "retry" field.
func (u *DnsZoneUpsert) AddRetry(v uint32) *DnsZoneUpsert {
	u.Add(dnszone.FieldRetry, v)
	return u
}

// SetExpire sets the "expire" field.
func (u *DnsZoneUpsert) SetExpire(v uint32) *DnsZoneUpsert {
	u.Set(dnszone.FieldExpire, v)
	return u
}

// UpdateExpire sets the "expire" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateExpire() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldExpire)
	return u
}

// AddExpire adds v to the "expire" field.
func (u *DnsZoneUpsert) AddExpire(v uint32) *DnsZoneUpsert {
	u.Add(dnszone.FieldExpire, v)
	return u
}

// SetMinttl sets the "minttl" field.
func (u *DnsZoneUpsert) SetMinttl(v uint32) *DnsZoneUpsert {
	u.Set(dnszone.FieldMinttl, v)
	return u
}

// UpdateMinttl sets the "minttl" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateMinttl() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldMinttl)
	return u
}

// AddMinttl adds v to the "minttl" field.
func (u *DnsZoneUpsert) AddMinttl(v uint32) *DnsZoneUpsert {
	u.Add(dnszone.FieldMinttl, v)
	return u
}

// SetActivated sets the "activated" field.
func (u *DnsZoneUpsert) SetActivated(v bool) *DnsZoneUpsert {
	u.Set(dnszone.FieldActivated, v)
	return u
}

// UpdateActivated sets the "activated" field to the value that was provided on create.
func (u *DnsZoneUpsert) UpdateActivated() *DnsZoneUpsert {
	u.SetExcluded(dnszone.FieldActivated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DnsZone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dnszone.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DnsZoneUpsertOne) UpdateNewValues() *DnsZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dnszone.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dnszone.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(dnszone.FieldName)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DnsZone.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DnsZoneUpsertOne) Ignore() *DnsZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DnsZoneUpsertOne) DoNothing() *DnsZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DnsZoneCreate.OnConflict
// documentation for more info.
func (u *DnsZoneUpsertOne) Update(set func(*DnsZoneUpsert)) *DnsZoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DnsZoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DnsZoneUpsertOne) SetUpdatedAt(v time.Time) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateUpdatedAt() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRrtype sets the "rrtype" field.
func (u *DnsZoneUpsertOne) SetRrtype(v uint16) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetRrtype(v)
	})
}

// AddRrtype adds v to the "rrtype" field.
func (u *DnsZoneUpsertOne) AddRrtype(v uint16) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddRrtype(v)
	})
}

// UpdateRrtype sets the "rrtype" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateRrtype() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateRrtype()
	})
}

// SetClass sets the "class" field.
func (u *DnsZoneUpsertOne) SetClass(v uint16) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetClass(v)
	})
}

// AddClass adds v to the "class" field.
func (u *DnsZoneUpsertOne) AddClass(v uint16) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddClass(v)
	})
}

// UpdateClass sets the "class" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateClass() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateClass()
	})
}

// SetTTL sets the "ttl" field.
func (u *DnsZoneUpsertOne) SetTTL(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetTTL(v)
	})
}

// AddTTL adds v to the "ttl" field.
func (u *DnsZoneUpsertOne) AddTTL(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddTTL(v)
	})
}

// UpdateTTL sets the "ttl" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateTTL() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateTTL()
	})
}

// SetNs sets the "ns" field.
func (u *DnsZoneUpsertOne) SetNs(v string) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetNs(v)
	})
}

// UpdateNs sets the "ns" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateNs() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateNs()
	})
}

// SetMbox sets the "mbox" field.
func (u *DnsZoneUpsertOne) SetMbox(v string) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetMbox(v)
	})
}

// UpdateMbox sets the "mbox" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateMbox() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateMbox()
	})
}

// SetSerial sets the "serial" field.
func (u *DnsZoneUpsertOne) SetSerial(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetSerial(v)
	})
}

// AddSerial adds v to the "serial" field.
func (u *DnsZoneUpsertOne) AddSerial(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateSerial() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateSerial()
	})
}

// SetRefresh sets the "refresh" field.
func (u *DnsZoneUpsertOne) SetRefresh(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetRefresh(v)
	})
}

// AddRefresh adds v to the "refresh" field.
func (u *DnsZoneUpsertOne) AddRefresh(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddRefresh(v)
	})
}

// UpdateRefresh sets the "refresh" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateRefresh() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateRefresh()
	})
}

// SetRetry sets the "retry" field.
func (u *DnsZoneUpsertOne) SetRetry(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetRetry(v)
	})
}

// AddRetry adds v to the "retry" field.
func (u *DnsZoneUpsertOne) AddRetry(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddRetry(v)
	})
}

// UpdateRetry sets the "retry" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateRetry() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateRetry()
	})
}

// SetExpire sets the "expire" field.
func (u *DnsZoneUpsertOne) SetExpire(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetExpire(v)
	})
}

// AddExpire adds v to the "expire" field.
func (u *DnsZoneUpsertOne) AddExpire(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddExpire(v)
	})
}

// UpdateExpire sets the "expire" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateExpire() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateExpire()
	})
}

// SetMinttl sets the "minttl" field.
func (u *DnsZoneUpsertOne) SetMinttl(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetMinttl(v)
	})
}

// AddMinttl adds v to the "minttl" field.
func (u *DnsZoneUpsertOne) AddMinttl(v uint32) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddMinttl(v)
	})
}

// UpdateMinttl sets the "minttl" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateMinttl() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateMinttl()
	})
}

// SetActivated sets the "activated" field.
func (u *DnsZoneUpsertOne) SetActivated(v bool) *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetActivated(v)
	})
}

// UpdateActivated sets the "activated" field to the value that was provided on create.
func (u *DnsZoneUpsertOne) UpdateActivated() *DnsZoneUpsertOne {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateActivated()
	})
}

// Exec executes the query.
func (u *DnsZoneUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DnsZoneCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DnsZoneUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DnsZoneUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DnsZoneUpsertOne.ID is not supported by MySQL driver. Use DnsZoneUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DnsZoneUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DnsZoneCreateBulk is the builder for creating many DnsZone entities in bulk.
type DnsZoneCreateBulk struct {
	config
	builders []*DnsZoneCreate
	conflict []sql.ConflictOption
}

// Save creates the DnsZone entities in the database.
func (dzcb *DnsZoneCreateBulk) Save(ctx context.Context) ([]*DnsZone, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dzcb.builders))
	nodes := make([]*DnsZone, len(dzcb.builders))
	mutators := make([]Mutator, len(dzcb.builders))
	for i := range dzcb.builders {
		func(i int, root context.Context) {
			builder := dzcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DnsZoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dzcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dzcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dzcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dzcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dzcb *DnsZoneCreateBulk) SaveX(ctx context.Context) []*DnsZone {
	v, err := dzcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dzcb *DnsZoneCreateBulk) Exec(ctx context.Context) error {
	_, err := dzcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dzcb *DnsZoneCreateBulk) ExecX(ctx context.Context) {
	if err := dzcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DnsZone.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DnsZoneUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (dzcb *DnsZoneCreateBulk) OnConflict(opts ...sql.ConflictOption) *DnsZoneUpsertBulk {
	dzcb.conflict = opts
	return &DnsZoneUpsertBulk{
		create: dzcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DnsZone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dzcb *DnsZoneCreateBulk) OnConflictColumns(columns ...string) *DnsZoneUpsertBulk {
	dzcb.conflict = append(dzcb.conflict, sql.ConflictColumns(columns...))
	return &DnsZoneUpsertBulk{
		create: dzcb,
	}
}

// DnsZoneUpsertBulk is the builder for "upsert"-ing
// a bulk of DnsZone nodes.
type DnsZoneUpsertBulk struct {
	create *DnsZoneCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DnsZone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dnszone.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DnsZoneUpsertBulk) UpdateNewValues() *DnsZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dnszone.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dnszone.FieldCreatedAt)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(dnszone.FieldName)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DnsZone.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DnsZoneUpsertBulk) Ignore() *DnsZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DnsZoneUpsertBulk) DoNothing() *DnsZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DnsZoneCreateBulk.OnConflict
// documentation for more info.
func (u *DnsZoneUpsertBulk) Update(set func(*DnsZoneUpsert)) *DnsZoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DnsZoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DnsZoneUpsertBulk) SetUpdatedAt(v time.Time) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateUpdatedAt() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRrtype sets the "rrtype" field.
func (u *DnsZoneUpsertBulk) SetRrtype(v uint16) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetRrtype(v)
	})
}

// AddRrtype adds v to the "rrtype" field.
func (u *DnsZoneUpsertBulk) AddRrtype(v uint16) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddRrtype(v)
	})
}

// UpdateRrtype sets the "rrtype" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateRrtype() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateRrtype()
	})
}

// SetClass sets the "class" field.
func (u *DnsZoneUpsertBulk) SetClass(v uint16) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetClass(v)
	})
}

// AddClass adds v to the "class" field.
func (u *DnsZoneUpsertBulk) AddClass(v uint16) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddClass(v)
	})
}

// UpdateClass sets the "class" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateClass() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateClass()
	})
}

// SetTTL sets the "ttl" field.
func (u *DnsZoneUpsertBulk) SetTTL(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetTTL(v)
	})
}

// AddTTL adds v to the "ttl" field.
func (u *DnsZoneUpsertBulk) AddTTL(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddTTL(v)
	})
}

// UpdateTTL sets the "ttl" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateTTL() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateTTL()
	})
}

// SetNs sets the "ns" field.
func (u *DnsZoneUpsertBulk) SetNs(v string) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetNs(v)
	})
}

// UpdateNs sets the "ns" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateNs() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateNs()
	})
}

// SetMbox sets the "mbox" field.
func (u *DnsZoneUpsertBulk) SetMbox(v string) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetMbox(v)
	})
}

// UpdateMbox sets the "mbox" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateMbox() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateMbox()
	})
}

// SetSerial sets the "serial" field.
func (u *DnsZoneUpsertBulk) SetSerial(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetSerial(v)
	})
}

// AddSerial adds v to the "serial" field.
func (u *DnsZoneUpsertBulk) AddSerial(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateSerial() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateSerial()
	})
}

// SetRefresh sets the "refresh" field.
func (u *DnsZoneUpsertBulk) SetRefresh(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetRefresh(v)
	})
}

// AddRefresh adds v to the "refresh" field.
func (u *DnsZoneUpsertBulk) AddRefresh(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddRefresh(v)
	})
}

// UpdateRefresh sets the "refresh" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateRefresh() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateRefresh()
	})
}

// SetRetry sets the "retry" field.
func (u *DnsZoneUpsertBulk) SetRetry(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetRetry(v)
	})
}

// AddRetry adds v to the "retry" field.
func (u *DnsZoneUpsertBulk) AddRetry(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddRetry(v)
	})
}

// UpdateRetry sets the "retry" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateRetry() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateRetry()
	})
}

// SetExpire sets the "expire" field.
func (u *DnsZoneUpsertBulk) SetExpire(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetExpire(v)
	})
}

// AddExpire adds v to the "expire" field.
func (u *DnsZoneUpsertBulk) AddExpire(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddExpire(v)
	})
}

// UpdateExpire sets the "expire" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateExpire() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateExpire()
	})
}

// SetMinttl sets the "minttl" field.
func (u *DnsZoneUpsertBulk) SetMinttl(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetMinttl(v)
	})
}

// AddMinttl adds v to the "minttl" field.
func (u *DnsZoneUpsertBulk) AddMinttl(v uint32) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.AddMinttl(v)
	})
}

// UpdateMinttl sets the "minttl" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateMinttl() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateMinttl()
	})
}

// SetActivated sets the "activated" field.
func (u *DnsZoneUpsertBulk) SetActivated(v bool) *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.SetActivated(v)
	})
}

// UpdateActivated sets the "activated" field to the value that was provided on create.
func (u *DnsZoneUpsertBulk) UpdateActivated() *DnsZoneUpsertBulk {
	return u.Update(func(s *DnsZoneUpsert) {
		s.UpdateActivated()
	})
}

// Exec executes the query.
func (u *DnsZoneUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DnsZoneCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DnsZoneCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DnsZoneUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
