name: coredns
summary: DNS server.
description: CoreDNS is a DNS server that chains plugins .
  
confinement: devmode
base: core18

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
    coredns:
    command: bin/coredns
    plugs:
      - home
      - network
      - removable-media
      - docker
      

parts:
  coredns:
    plugin: go
    source: https://github.com/coredns/coredns.git
    source-type: git
    override-pull: |
      git clone https://github.com/coredns/coredns.git src/github.com/coredns/coredns
      cd src/github.com/coredns/coredns
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
    override-build: |
      export GOPATH=$PWD
      cd src/github.com/coredns/coredns
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/coredns/coredns/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/coredns/coredns/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/coredns
    build-snaps:
      - go
    build-packages:
      - git
      - sed
