name: Docker Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release (e.g., v1.9.0)"
        required: true

jobs:
  docker-release:
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      RELEASE: ${{ github.event.inputs.release || github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: |
          set -x -e
          make VERSION=${RELEASE:1} DOCKER=yongtang -f Makefile.docker release
          docker images
      - name: Publish Docker Images
        run: |
          set -x -e
          make VERSION=${RELEASE:1} DOCKER=yongtang -f Makefile.docker docker-push
